version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: local-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:3.8.0
    container_name: local-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /kafka/kraft-combined-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/kafka/kraft-combined-logs
    command: |
      bash -c '
        # 최초 실행 시에만 메타파일이 없으면 포맷 수행
        if [ ! -f "/kafka/kraft-combined-logs/meta.properties" ]; then
          CLUSTER_ID=$(/opt/kafka/bin/kafka-storage.sh random-uuid)
          /opt/kafka/bin/kafka-storage.sh format \
            --cluster-id "$CLUSTER_ID" \
            --config /opt/kafka/config/kraft/server.properties
        fi
        # 브로커 기동
        exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
      '

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "10000:10000"
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 10000
      # 로컬 KRaft 모드 브로커(9092) 연결
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: local-kafka:9092
      # Zookeeper 미사용 시 빈 값
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""

volumes:
  mysql_data:
  kafka_data: